/** IcebreakerBot question content. Pure data — no logic here. All original, English, short,
 * safe for a general audience, and written to work for any group (no assumptions about
 * relationships, family structure, religion, or politics).
 * GENERAL = 190 (free tier, fixed daily pack). Each theme = 35 (Pro only). Total = 365. */

export const THEMES = ["fun", "deep", "work", "travel", "food"] as const;
export type Theme = (typeof THEMES)[number];

export const THEME_LABEL: Record<Theme, string> = {
  fun: "🎈 Fun",
  deep: "🌊 Deep",
  work: "💼 Work",
  travel: "✈️ Travel",
  food: "🍜 Food",
};

export const GENERAL: string[] = [
  "What's a small thing that made you smile this week?",
  "If you could instantly become an expert in one skill, what would it be?",
  "What's a song that always puts you in a good mood?",
  "What's the best piece of advice you've ever received?",
  "If you had an extra hour every day, how would you spend it?",
  "What's a hobby you've always wanted to try but haven't yet?",
  "What's your go-to comfort food?",
  "What's a book or show that changed how you think about something?",
  "What's the last thing that made you laugh out loud?",
  "If you could have dinner with anyone, living or fictional, who would it be?",
  "What's a skill you're proud of learning?",
  "What's your favorite way to spend a lazy Sunday?",
  "What's a place you've never been but really want to visit?",
  "What's the most useful app on your phone?",
  "What's a tradition from your family or culture that you love?",
  "If you could master a musical instrument overnight, which would you choose?",
  "What's a small daily habit that makes a big difference for you?",
  "What's your favorite season and why?",
  "What's a movie you could watch on repeat?",
  "If you woke up with a new talent tomorrow, what would you want it to be?",
  "What's the best gift you've ever given someone?",
  "What's a childhood memory that still makes you happy?",
  "What's something you're really curious about right now?",
  "What's your favorite way to unwind after a long day?",
  "If you could time travel to any decade, which would you pick?",
  "What's a food you were scared to try but ended up loving?",
  "What's the most spontaneous thing you've ever done?",
  "What's a quote or saying you live by?",
  "What's your ideal way to spend a rainy afternoon?",
  "What's something you learned this year that surprised you?",
  "If you could learn any language instantly, which would you choose?",
  "What's your favorite smell and why?",
  "What's a game you loved as a kid?",
  "What's the best concert or live event you've been to?",
  "If you had a theme song, what would it be?",
  "What's a small act of kindness someone did for you that you still remember?",
  "What's your favorite way to start the morning?",
  "What's something on your bucket list?",
  "What's a skill you think everyone should learn?",
  "What's your favorite type of weather?",
  "If you could redesign your living space, what's the first thing you'd change?",
  "What's a compliment you received that stuck with you?",
  "What's your favorite holiday and what makes it special?",
  "What's a topic you could talk about for hours?",
  "What's something that always cheers you up?",
  "If you could try any job for a day, what would you pick?",
  "What's a place that feels like home to you?",
  "What's your favorite way to celebrate good news?",
  "What's a lesson you learned the hard way?",
  "What's your favorite thing about this group?",
  "What's a hobby that helps you relax?",
  "If you could instantly declutter one part of your life, what would it be?",
  "What's your favorite kind of music to listen to while working?",
  "What's a fun fact about yourself most people don't know?",
  "What's a simple pleasure you enjoy every day?",
  "What's your favorite way to explore a new city?",
  "If you could keep any animal as a pet, real or imaginary, what would it be?",
  "What's a goal you're currently working toward?",
  "What's your favorite meal to cook for others?",
  "What's something you've gotten better at over the years?",
  "What's your favorite thing to do with friends?",
  "If you could send a message to your younger self, what would it say?",
  "What's a color that describes your mood today?",
  "What outdoor spot always clears your head?",
  "What's a piece of technology you couldn't live without?",
  "What's something you're grateful for today?",
  "What's your favorite type of story to read or watch?",
  "If you could plan the perfect weekend, what would it look like?",
  "What's a skill from your childhood you still use today?",
  "What's your favorite thing about where you live?",
  "What's the most interesting thing you've learned recently?",
  "If you had to describe your personality in three words, what would they be?",
  "What's your favorite way to make new friends?",
  "What's a small goal you achieved that you're proud of?",
  "What's your favorite thing to do on a day off?",
  "If you could visit any fictional world, which one would you choose?",
  "What's your favorite thing about mornings?",
  "What's a memory that always makes you laugh?",
  "What's something you'd like to get better at this year?",
  "What's your favorite way to give back or help others?",
  "What's a routine that keeps you feeling balanced?",
  "If you could have any superpower for a day, what would you do with it?",
  "What's your favorite thing about the current season?",
  "What's a word in another language you wish existed in English?",
  "What's your favorite way to celebrate a small win?",
  "What's something that instantly puts you in a good mood?",
  "If you could learn from any historical figure, who would you pick?",
  "What's your favorite kind of weather to relax in?",
  "What's a skill you'd love to teach someone else?",
  "What's your favorite childhood snack?",
  "What's the most useful thing you own?",
  "If you could switch lives with someone for a day, who would it be?",
  "What's your favorite way to recharge on a busy week?",
  "What's something you've always wanted to learn to make or build?",
  "What's your favorite thing about your neighborhood?",
  "What's a small win you had today?",
  "If you could have any view outside your window, what would it be?",
  "Which family tradition would you never want to lose?",
  "What's something you're looking forward to this month?",
  "What's a habit you'd like to start?",
  "What's your favorite thing to collect or have collected?",
  "If you could learn to play any sport really well, which would it be?",
  "What's your favorite kind of vacation?",
  "What's a piece of advice you'd give to someone just starting out in life?",
  "What's your favorite way to stay curious?",
  "What's the most beautiful place you've ever seen?",
  "If you could design your dream room, what would be in it?",
  "What's your favorite thing to do when it's sunny outside?",
  "What's a small change that made your life easier?",
  "What's your ideal way to wind down after a long day?",
  "If you could master any craft, what would you make?",
  "What's something you do differently now than you did five years ago?",
  "What's your favorite thing about weekends?",
  "What's a story from your life that always gets a good reaction?",
  "What's your favorite way to celebrate birthdays?",
  "If you could add a new tradition to your life, what would it be?",
  "What's the most rewarding thing you've done recently?",
  "What's your favorite way to be creative?",
  "What's a skill you picked up just for fun?",
  "What's your favorite thing to notice on a walk?",
  "If you could relive one day exactly as it happened, which would you pick?",
  "What's your favorite way to greet the day?",
  "What's a small luxury that makes your day better?",
  "What's your favorite thing about your favorite hobby?",
  "If you could instantly organize one area of your life, which would it be?",
  "What's your favorite way to celebrate the little things?",
  "What's a fact you love sharing with others?",
  "What's your favorite thing about your daily routine?",
  "If you could try a new hobby this month, what would you pick?",
  "What's your favorite thing to do with a free afternoon?",
  "What's a moment this year you're grateful for?",
  "What's your favorite kind of music to dance to?",
  "If you could master any language for travel, which would you choose?",
  "What's your favorite thing to do to relax your mind?",
  "What's a small tradition you have with a friend?",
  "What does a perfect solo afternoon look like for you?",
  "If you could pick a theme song for your week, what would it be?",
  "What's your favorite thing about your morning routine?",
  "What's a lesson from a mistake that stuck with you?",
  "What's your favorite way to explore new ideas?",
  "If you could bring back one trend from the past, what would it be?",
  "What sound, or silence, helps you relax the most?",
  "What's a small habit that improved your mood?",
  "What's your favorite thing to learn about?",
  "If you could instantly pick up a new skill for your job or studies, what would it be?",
  "What's your favorite way to celebrate progress?",
  "What's a place near you that you love visiting?",
  "What's your favorite thing about being part of this community?",
  "If you could design a perfect day from start to finish, what would it include?",
  "What's your favorite way to stay motivated?",
  "What's a small comfort you enjoy every day?",
  "What's your favorite type of conversation to have?",
  "If you could try any extreme hobby just once, what would it be?",
  "What's your favorite thing about your closest friendships?",
  "What's a moment that made you feel proud of yourself?",
  "What's your favorite way to spend time with people you care about?",
  "If you could ask your future self one question, what would it be?",
  "What's your favorite thing about learning something new?",
  "What's a small joy you experienced today?",
  "What's your favorite way to end the day?",
  "If you could have an unlimited supply of one thing, what would it be?",
  "What's your favorite thing about your hometown?",
  "What's a hobby that always surprises people when they hear about it?",
  "What's your favorite way to spend the first hour of your day?",
  "If you could relive one happy memory, which would you choose?",
  "What's your favorite thing to do that costs nothing?",
  "What's a random fact you know that always impresses people?",
  "What's your favorite way to celebrate a friend's success?",
  "If you could pick up an instrument and be great at it instantly, what would you choose?",
  "What's your favorite thing about the weekend so far?",
  "What's a small thing you're thankful for right now?",
  "What's one thing you'd love this group to do together sometime?",
  "If you could visit any era in history just to observe, which would you choose?",
  "What's your favorite thing to do when you need a mental break?",
  "What's a habit you're proud of keeping up?",
  "What's your favorite way to try something new?",
  "If you could master a new recipe this week, what would it be?",
  "What's your favorite thing about your morning coffee or tea?",
  "What's a small detail about today that stood out to you?",
  "If you had a surprise free evening, what would you do with it?",
  "If you could give your past self one piece of advice, what would it be?",
  "What's your favorite thing about spending time outdoors?",
  "What's a small moment of joy from this week?",
  "What's your favorite way to connect with people you don't see often?",
  "If you could learn one new thing every day for a year, what topic would you choose?",
  "What's your favorite thing about today so far?",
  "What's a memory you'd love to relive just once more?",
  "What's your favorite way to wind down before bed?",
  "What's something small that always makes your day better?",
  "What's your favorite thing about this time of year?",
];

const FUN: string[] = [
  "Would you rather have the ability to fly or be invisible?",
  "What's the silliest thing that's ever made you laugh?",
  "If you could have any cartoon character's power, who would you pick?",
  "Would you rather always speak in rhymes or always sing your sentences?",
  "What's the weirdest food combination you actually enjoy?",
  "If your life had a laugh track, what moment would trigger it most?",
  "Would you rather explore space or the deep ocean?",
  "What's the most ridiculous nickname you've ever had?",
  "If you could swap lives with a fictional character for a day, who would it be?",
  "Would you rather never use emojis again or only communicate in emojis?",
  "What's a silly talent you have that isn't very useful?",
  "If animals could talk, which one would be the funniest?",
  "Would you rather be able to teleport or read minds?",
  "What's the most fun you've had doing something totally pointless?",
  "If you had a personal theme song that played everywhere you went, what genre would it be?",
  "Would you rather fight one horse-sized duck or a hundred duck-sized horses?",
  "What's the goofiest costume you've ever worn?",
  "If you could turn any everyday object into a superhero gadget, what would you pick?",
  "Would you rather have permanent confetti falling around you or permanent applause?",
  "What's the funniest prank you've seen or been part of?",
  "If your pet, real or imaginary, could talk, what would it complain about most?",
  "Would you rather be a stand-up comedian for a night or a rockstar for a night?",
  "What's the most fun game you've played that most people haven't heard of?",
  "If you could instantly win any competition, what would you choose?",
  "Would you rather have a rewind button or a pause button for your life?",
  "What's the silliest rule you had to follow as a kid?",
  "If you could be any snack food, what would you be and why?",
  "Would you rather always have to dance into a room or always make an entrance sound effect?",
  "What's a game night moment you'll never forget?",
  "If you could add one ridiculous law to your city, what would it be?",
  "Would you rather have glow-in-the-dark hair or sparkly skin?",
  "What's the funniest thing that's happened to you this month?",
  "If you could star in any movie genre for a day, which would you pick?",
  "Would you rather talk like a pirate or a robot for a week?",
  "What's the most fun way you've celebrated a random Tuesday?",
];

const DEEP: string[] = [
  "What does \"success\" mean to you personally?",
  "What's a belief you hold that has changed over time?",
  "What does being truly present look like for you?",
  "What's something you've learned about yourself this year?",
  "What does a meaningful life look like to you?",
  "What's a value you refuse to compromise on?",
  "What's something you used to worry about that doesn't matter to you anymore?",
  "What does gratitude look like in your everyday life?",
  "What's a moment that shifted how you see the world?",
  "What does it mean to you to be a good friend?",
  "What's something you're still learning to accept about yourself?",
  "What's a question you wish more people asked each other?",
  "What does courage look like in ordinary, everyday moments?",
  "What's something you value more now than you did five years ago?",
  "What does \"home\" mean to you beyond a physical place?",
  "What's a lesson that took you a long time to truly understand?",
  "What does it mean to live with intention?",
  "What's something you appreciate about the people closest to you?",
  "What does resilience look like when things get hard?",
  "What's a small moment that taught you something big?",
  "What does it mean to you to grow as a person?",
  "What's something you'd want people to remember about you?",
  "What does balance look like in your life right now?",
  "What's a fear you've slowly learned to face?",
  "What does connection mean to you in a world full of distractions?",
  "What's something you're proud of that no one else knows about?",
  "What does it mean to forgive, in your experience?",
  "What's a piece of wisdom you'd pass on to the next generation?",
  "What does contentment feel like for you?",
  "What's something that helped you through a hard chapter in your life?",
  "What does authenticity mean to you?",
  "What's a question about life you still don't have an answer to?",
  "What does it mean to you to show up for someone?",
  "What's a change in perspective that made you a happier person?",
  "What does it mean to you to leave things better than you found them?",
];

const WORK: string[] = [
  "What's the best piece of career advice you've ever gotten?",
  "What does a productive day look like for you?",
  "What's a work habit you're proud of building?",
  "What's the most useful tool you use at work?",
  "What's a project you're proud of finishing?",
  "What does good teamwork look like to you?",
  "What's a skill you've picked up on the job that surprised you?",
  "What's your favorite way to start a workday?",
  "What's a piece of feedback that helped you grow professionally?",
  "What does work-life balance mean to you right now?",
  "What's the best team you've ever been part of, and what made it great?",
  "What's a small change that made your workday smoother?",
  "What's a goal you're working toward this quarter?",
  "What does a good leader do differently, in your experience?",
  "What's a mistake at work that taught you something valuable?",
  "What's your favorite part of your current role?",
  "What's a skill you'd like to develop this year?",
  "What does an ideal work environment look like to you?",
  "What's the most interesting problem you've solved recently?",
  "What's a habit that keeps you focused during a busy day?",
  "What's something you learned from a mentor or colleague?",
  "What does career growth look like for you right now?",
  "What's a tool or app that's made your work life easier?",
  "What's the most rewarding part of what you do?",
  "What's a decision at work you're glad you made?",
  "What does a great meeting look like to you?",
  "What's a strength you bring to your team?",
  "What's something you wish you'd known earlier in your career?",
  "What does staying motivated look like on a tough week?",
  "What's a way your work has changed you for the better?",
  "What's the best advice you'd give someone starting their first job?",
  "What does celebrating a win at work look like for you?",
  "What's a skill from outside of work that helps you in your job?",
  "What's something small that boosts morale on your team?",
  "What does taking a real break during the workday look like for you?",
];

const TRAVEL: string[] = [
  "What trip taught you something you didn't expect?",
  "If you could teleport anywhere right now, where would you go?",
  "What's a destination that's been on your list for years?",
  "What's the best meal you've had while traveling?",
  "What's a travel memory that still makes you smile?",
  "What's your favorite way to explore a new place?",
  "What's the most beautiful view you've ever seen?",
  "If you could live in another country for a year, where would you choose?",
  "What's a travel tip you swear by?",
  "What's a trip you booked on a total whim?",
  "What's a place you'd love to visit again?",
  "What's the most interesting person you've met while traveling?",
  "What's your dream road trip route?",
  "What's a local custom from another place that you loved?",
  "What's the best souvenir you've ever brought home?",
  "If you could only pack one bag for a year of travel, what's in it?",
  "What's a city you'd love to explore on foot?",
  "What's the most adventurous thing you've done while traveling?",
  "What's a place that felt completely different from what you expected?",
  "What's your favorite way to travel: road trip, train, or plane?",
  "What's a festival or event you'd love to attend somewhere in the world?",
  "What's a trip that flew by faster than you expected?",
  "What's a hidden gem you discovered while traveling?",
  "What's a language you'd love to learn before visiting a country?",
  "What's your ideal way to spend a day in a new city?",
  "What's a place you'd recommend to a first-time visitor?",
  "Where do you go when you just want to switch off completely?",
  "What's a travel goal you have for the next few years?",
  "What's something you always pack, no matter where you're going?",
  "What's the most unique place you've ever stayed?",
  "What's a food you first tried while traveling that you still crave?",
  "What's a country whose culture fascinates you?",
  "What's your favorite travel memory with friends or family?",
  "What's a place near home that feels like a mini getaway?",
  "What's the next trip you're dreaming about?",
];

const FOOD: string[] = [
  "What's your ultimate comfort food?",
  "What's a dish you make better than anyone else you know?",
  "What's the best meal you've ever had?",
  "What's a food you didn't like as a kid but love now?",
  "What's your favorite cuisine to order in?",
  "What's a recipe you'd love to learn to make?",
  "What's your go-to snack when you need a pick-me-up?",
  "What's the best homemade meal someone has ever cooked for you?",
  "What's a dish from your childhood you still crave?",
  "What's your favorite thing to bake?",
  "What's a food trend you actually love?",
  "What's the spiciest thing you've ever eaten?",
  "What's your favorite breakfast to start the day?",
  "What's a meal that instantly feels like home?",
  "What's a dish you'd love to master this year?",
  "What's your favorite way to spend a Sunday cooking?",
  "What's a food combination people think is strange but you swear by?",
  "What's the best street food you've ever had?",
  "What's your favorite dessert of all time?",
  "What's a cuisine you'd love to explore more?",
  "What's the first thing you learned to cook?",
  "What's your favorite meal to share with a group?",
  "What's a food memory tied to a special occasion?",
  "What's a warm drink you always reach for when it's cold out?",
  "What's a restaurant dish you wish you could recreate at home?",
  "What's your favorite way to use leftovers?",
  "What's a food you could eat every day and never get tired of?",
  "What's the most adventurous food you've ever tried?",
  "What's your favorite comfort meal on a rainy day?",
  "What's a family recipe that means a lot to you?",
  "What's your favorite thing to grill or cook outdoors?",
  "What's a snack you always have on hand?",
  "What's the best coffee or tea you've ever had?",
  "What's your favorite meal to celebrate with?",
  "What's a food you're determined to try someday?",
];

export const PACKS: Record<Theme, string[]> = { fun: FUN, deep: DEEP, work: WORK, travel: TRAVEL, food: FOOD };
